### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by rangicus** [devanhurst/ktane_voice#1]
After running the included commands in ruby: [image](http://i.imgur.com/b4HorHt.png)

**Comment by natdempk** [comment]
According to the docs for [pocketsphinx-ruby](https://github.com/watsonbox/pocketsphinx-ruby) you probably need to install [Pocketsphinx ](https://github.com/cmusphinx/pocketsphinx)and [Sphinxbase](https://github.com/cmusphinx/sphinxbase).

There are instructions for installing both of those in their linked repo READMEs. Afterwards you should be able to run the install commands successfully:

```
bundle
ruby charlie.rb
```

This may be worth noting in the README that this doesn't happen as part of the `bundle` process on windows (and potentially other OSes?) by default.

**Comment by devanhurst** [comment]
Running bundle will install the pocketsphinx-ruby gem on OSX, which will in turn install all its dependencies, IIRC. I haven't tested on any other OS and would happily pull an updated README if anyone makes a pull request with added instructions.

**Comment by gerrywastaken** [comment]
@devanhurst Running bundle install will only install Ruby dependencies. As mentioned by @natdempk, the system dependencies will need to be installed in the same way that is described by pocketsphinx-ruby: https://github.com/watsonbox/pocketsphinx-ruby#installation

Just to clarify, I run osx and bundle did not include these system dependencies.

**Comment by devanhurst** [comment]
You're right. It was so long ago that I installed Pocketsphinx that I forgot all about this step. I'll add it to the readme.

**Comment by BrunoMoreira99** [comment]
I'm sorry for discussing this on a closed issue but I need some assistance on getting the required libraries Pocketsphinx (libpocketsphinx) and Sphinxbase (libsphinxbase and libsphinxad).

Since I am on Windows I suppose I need to build them manually using MS Visual Studio.
I don't have any experience on Ruby by the way, I'm currently learning C/C++, VB and PHP.

Well, I compiled the solutions and the only .dll it built were sphinxbase.dll and pocketsphinx.dll (don't even know if those are the right ones, if they are then I believe I need to rename them to libsphinxbase.dll and libpocketsphinx.dll?) but it's still missing libsphinxad.dll (at least according to the output).

If anyone with experience on this matter for Windows could help me get this files then maybe I could add instructions to the readme about Windows procedures.

**Comment by devanhurst** [comment]
@BrunoMoreira991 Would you mind opening another issue? I'd like others to see that Windows installation still needs to be solved. :)
